sudo: false
build_image: drydock/u14pytpls:prod
language: python
python:
  - 2.6
  - 2.7
  - pypy
  - 3.3
  - 3.4
  - 3.5
addons:
  postgresql: '9.4'
install:
  - pip install -r test-requirements.txt
  - if [[ $TRAVIS_PYTHON_VERSION == '2.6' ]]; then pip install unittest2 --download-cache $HOME/.pip-cache; fi
  - python setup.py develop
script: nosetests
